sensor:
  - platform: rest
    name: Left blinds Current Angle
    unique_id: blinds_left_angle
    resource: http://192.168.107.61/servo
    method: GET
    value_template: "{{ value_json.angle }}"
    unit_of_measurement: "°"
    scan_interval: 60
  - platform: rest
    name: Right blinds Current Angle
    unique_id: blinds_right_angle
    resource: http://192.168.107.101/servo
    method: GET
    value_template: "{{ value_json.angle }}"
    unit_of_measurement: "°"
    scan_interval: 60
